stages:
  - build

build_docker_image:
  stage: build
  image: docker:26.1.4-cli
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_IMAGE_NAME: "DOCKER_IMAGE_NAME"
  script:
    - docker login -u "$docker_username" -p "$docker_wachtwoord"
    - docker build --pull -t "DOCKER_IMAGE_NAME" .
    - docker push "DOCKER_IMAGE_NAME"