stages:
    - build

build_docker_image:
    stage: build
    image: docker:26.1.4-cli
    services:
        - docker:dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
        DOCKER_IMAGE_NAME: "testdeployment"
    script:
        - docker build --pull -t "$testdeployment" .
        - docker run "$testdeployment"